architecture: YOLOv3 #读取“模型选择”下拉栏中展示的所有文件结果。注意大小写
use_gpu: true #是否使用gpu，是为true，否为false
max_iters: 20000 #最大迭代次数，默认为20000，可以在UI里额外设置一个端口更改这个值
log_iter: 20 #日志打印间隔，不用管，默认20
save_dir: output #模型保存地址，会生成一个/output的文件夹，默认值，不用管
snapshot_iter: 200 #模型保存间隔，不用管
metric: VOC #数据集格式和评估类型，可选择VOC或者COCO，先默认选择VOC格式
map_type: 11point #这是个多余的参数，不用加
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1.tar #预训练模型下载地址
weights: output/yolov3_mobilenet_v1_fruit/best_model #模型保存地址
num_classes: 3 #标签数，这个和数据集存储模块的统计数据相关联
finetune_exclude_pretrained_params: ["yolo_output"] #多于参数，不用管
use_fine_grained_loss: false #默认设置为false

YOLOv3:
  backbone: MobileNet #对应“backbones选择”下拉选框的结果
  yolo_head: YOLOv3Head #对应“模型选择”下拉选框结果，我们初期统一只是用yolov3

MobileNet: #backbones选了什么，这里就用相应的backbones名字开头
  norm_type: sync_bn
  norm_decay: 0.
  conv_group_scale: 1
  with_extra_blocks: false

YOLOv3Head: #对应上方yolo_head的参数值，下面的具体参数需要参照anchor head文件夹下的相应.py文件中的默认值
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors:
    [
      [10, 13],
      [16, 30],
      [33, 23],
      [30, 61],
      [62, 45],
      [59, 119],
      [116, 90],
      [156, 198],
      [373, 326],
    ]
  norm_decay: 0.   #默认值不用管
  yolo_loss: YOLOv3Loss #如果选择了YOLO模型，则使用yolo_loss，参数值为architecture参数的值+“Loss”
  nms: #以下均为默认值，不用管
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss: #对应yolo_loss 的参数值，下面的值为默认值不用管
  ignore_thresh: 0.7
  label_smooth: true

LearningRate:
  base_lr: 0.00001 #学习率learning rate，读取UI中的端口输入值
  schedulers: #以下参数均为默认值不用管
    - !PiecewiseDecay
      gamma: 0.1
      milestones:
        - 15000
        - 18000
    - !LinearWarmup
      start_factor: 0.
      steps: 100

OptimizerBuilder: #以下参数均为默认值不用管
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

#_READER_: 'yolov3_reader.yml'
# will merge TrainReader into yolov3_reader.yml
TrainReader:
  inputs_def:
    image_shape: [3, 608, 608] #后两位的数值均为UI中“最长长度”端口的设置值，这部分和数据存储模块中的统计数据相关
    fields: ["image", "gt_bbox", "gt_class", "gt_score"]
    num_max_boxes: 50
    use_dataloader: false
  dataset: !VOCDataSet #如果选择metric参数设置为VOC，则使用默认值。若为COCO，则将VOC改为COCO
    dataset_dir: fruit #data文件夹中的相应数据集文件夹名，这部分和数据存储模块的默认数据集储存地址相关
    anno_path: train.txt #相应数据集文件夹中的训练集列表文件名
    with_background: false
    use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: true
      with_mixup: false
    - !NormalizeBox {}
    - !ExpandImage
      max_ratio: 4.0
      mean: [123.675, 116.28, 103.53]
      prob: 0.5
    - !RandomInterpImage
      max_size: 0
      target_size: 608
    - !RandomFlipImage
      is_normalized: true
      prob: 0.5
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: true
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
    - !RandomShape
      sizes: [608] #最大长度值
    - !Permute
      channel_first: true
      to_bgr: false
  batch_size: 1 #对应UI端口中的批大小参数值
  shuffle: true
  mixup_epoch: -1

EvalReader:
  batch_size: 1 #对应UI端口中的批大小参数值
  inputs_def:
    image_shape: [3, 608, 608] #同上参数设置
    fields: ["image", "im_size", "im_id", "gt_bbox", "gt_class", "is_difficult"]
    num_max_boxes: 50
  dataset: !VOCDataSet #同上参数设置
    dataset_dir: fruit #同上参数设置
    anno_path: val.txt #相应数据集文件夹中的验证集列表文件名
    use_default_label: false
    with_background: false

TestReader:
  batch_size: 1 #对应UI端口中的批大小参数值
  dataset: !ImageFolder
    anno_path: fruit/label_list.txt #相应数据集文件夹中label_list.txt文件
    use_default_label: false
    with_background: false
