# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fedvision.framework.protobuf import cluster_pb2 as fedvision_dot_framework_dot_protobuf_dot_cluster__pb2


class ClusterManagerStub(object):
    """service in cluster manager called by worker
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_stream(
                '/fedvision.framework.cluster.ClusterManager/Enroll',
                request_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.Enroll.REQ.SerializeToString,
                response_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.Enroll.REP.FromString,
                )
        self.UpdateTaskStatus = channel.unary_unary(
                '/fedvision.framework.cluster.ClusterManager/UpdateTaskStatus',
                request_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.UpdateStatus.REQ.SerializeToString,
                response_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.UpdateStatus.REP.FromString,
                )
        self.TaskSubmit = channel.unary_unary(
                '/fedvision.framework.cluster.ClusterManager/TaskSubmit',
                request_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskSubmit.REQ.SerializeToString,
                response_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskSubmit.REP.FromString,
                )
        self.TaskResourceRequire = channel.unary_unary(
                '/fedvision.framework.cluster.ClusterManager/TaskResourceRequire',
                request_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskResourceRequire.REQ.SerializeToString,
                response_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskResourceRequire.REP.FromString,
                )


class ClusterManagerServicer(object):
    """service in cluster manager called by worker
    """

    def Enroll(self, request, context):
        """service for worker: enroll and fetch tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskStatus(self, request, context):
        """service for worker: update status or heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskSubmit(self, request, context):
        """service for master: submit task to cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskResourceRequire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_stream_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.Enroll.REQ.FromString,
                    response_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.Enroll.REP.SerializeToString,
            ),
            'UpdateTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskStatus,
                    request_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.UpdateStatus.REQ.FromString,
                    response_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.UpdateStatus.REP.SerializeToString,
            ),
            'TaskSubmit': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskSubmit,
                    request_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskSubmit.REQ.FromString,
                    response_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskSubmit.REP.SerializeToString,
            ),
            'TaskResourceRequire': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskResourceRequire,
                    request_deserializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskResourceRequire.REQ.FromString,
                    response_serializer=fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskResourceRequire.REP.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedvision.framework.cluster.ClusterManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClusterManager(object):
    """service in cluster manager called by worker
    """

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fedvision.framework.cluster.ClusterManager/Enroll',
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.Enroll.REQ.SerializeToString,
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.Enroll.REP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fedvision.framework.cluster.ClusterManager/UpdateTaskStatus',
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.UpdateStatus.REQ.SerializeToString,
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.UpdateStatus.REP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TaskSubmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fedvision.framework.cluster.ClusterManager/TaskSubmit',
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskSubmit.REQ.SerializeToString,
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskSubmit.REP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TaskResourceRequire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fedvision.framework.cluster.ClusterManager/TaskResourceRequire',
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskResourceRequire.REQ.SerializeToString,
            fedvision_dot_framework_dot_protobuf_dot_cluster__pb2.TaskResourceRequire.REP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
